feat: added sorting & pagination to point leaderboard + rpc fix
mrgnlabs/mrgn-ts pull request #159
Opened 2023-07-06 20:33 UTC by k0beLeenders

2023-07-07 06:24 UTC, edgarpavlovsky approved these changes
@k0beLeenders ltgm overall - left a small comment but should not be blocking

2023-07-07 06:24 UTC, edgarpavlovsky commented on apps/marginfi-v2-ui/src/components/Points/PointsLeaderBoard/PointsBoardHeader/PointsBoardHeader.consts.ts
> +    id: "total_referral_borrow_points",
nit - the `id` here should just generally refer to the head cell (not to what shows in the actual data), but technically this column will be deposit + borrow referral points

2023-07-07 06:31 UTC, edgarpavlovsky requested changes
sorry - few comments after playing around with it live (overall looks good, table is clean!):

* sorting arrow shows up on the right side of words in some cells and left side in others - can we standardize them all to be right side of word?
* let's move to first click on sort button being descending - intuition tells me people are likely to be more interested in who's at the top than the bottom. this will be the opposite for the `rank` column but given rank and total points are the same i think we can just disable rank column sorting
* it'd be nice to show people that they can sort - right now you have to hover over the words to see that the arrow's available. not sure what's aesthetically most pleasing here

other than that, super clean! i love seeing how loading is handled behind the scenes, experience feels quick

2023-07-07 18:27 UTC, k0beLeenders commented
Implemented the requested changes @edgarpavlovsky , I can set the arrows to always active if you want?

2023-07-07 18:34 UTC, edgarpavlovsky commented
yeah let's set arrows to always active @k0beLeenders

2023-07-07 18:35 UTC, edgarpavlovsky approved these changes

2023-07-10 14:55 UTC, edgarpavlovsky commented
![image](https://github.com/mrgnlabs/mrgn-ts/assets/12037214/bda2ae87-5f9b-4299-866f-df0e51de9189)

2023-07-10 14:55 UTC, merged